### ISSUE TITLE
Could not load analysis.json

### ISSUE THREAD

**Issue by daniel-vlad** [homerjonathan/jas-breadcrumbs#1]
Hey,

I cloned the repo, did a `bower install` and when i tried `polymer serve --open` i got `Could not load descriptor "analysis.json".  Error: The request failed with status code: 404`.

Am I missing a step here?

**Comment by homerjonathan** [comment]
Hi

I think the error sounds like a Polymer configuration problem. My component
doesn't use analysis.json. Is this your first time with Polymer? Check that
out first. If you are still stuck I will check it out later today.

Jon

**Comment by daniel-vlad** [comment]
Hi,

Thanks, i'll try and see if it's something with the polymer config. Thing is i have not done anything special, jut cloned the repo and served it. I've been playing with Polymer since a bit before 2.0 was in RC only, so i'm kind of new to it.

Using polymer-cli 1.2.0 if it helps any.

Daniel

**Comment by homerjonathan** [comment]
Hi Daniel

Managed to reproduce it on my system too.  It seems that it is an old
development dependency that load's a clever demo viewing system that
doesn't work.  I have updated the version to 0.2.9.  It should be rolled
out in the next twenty minutes or so.

I took out the dependency.  You may need to delete your bower_components
file and rerun bower install to throw out the offending code.

To access the demo you will need to enter:

http://127.0.0.1:8081/components/jas-breadcrumbs/demo/index.html

Thanks for spotting the error.

Jon

**Comment by homerjonathan** [comment]
Problem with old devDependencies.  Line removed.
```json
"iron-component-page": "^3.0.0"
```
This creates some kind of demo demonstrator code. Which also errors with the above analysis.json file.

You may need to delete bower_components and re-run **bower install** to repair previous version.
